### ISSUE TITLE
Feature Request: Add functionality to crawl "Directory Lister" sites.

### ISSUE THREAD

**Issue by FiZiX** [simon987/od-database#3] opened 2018-09-11 20:18 UTC
I looked at the crawler code briefly and it looks like it should be able to parse href tags. However, it doesn't seem to be able to crawl "Directory Lister" sites. Example here:

https://www.reddit.com/r/opendirectories/comments/9f0vfs/north_miami_police_transparency_files/

Would this functionality be worth adding?

**Comment by simon987** [comment] 2018-09-11 21:21
The HTML parser relies on the fact that link to directories ends with a forward slash and that any other link is a file.
This website's links look like this: `<a href="?dir=voice_messages"` and there is no way for the parser to tell that this is a directory (a page that should be visited) or a file (an url at which to send an `HEAD` request)

If someone can find a reliable way to differentiate a file from a directory I'd be happy to implement it

**Comment by simon987** [comment] 2018-09-12 00:35
Yes, this is the case for this website but some other website might have `?folder=` or `?path=` or `?directory=`.
It needs to work for every single website

**Comment by FiZiX** [comment] 2018-09-12 00:45
I see what you mean. I was asking specifically about sites generated by this script:

https://github.com/DirectoryLister/DirectoryLister

But it's probably not worth the effort due to the number of other directory listing scripts people may be using.

**Comment by terorie** [comment] 2019-02-10 23:10
Closing this for now because the site in question isn't really a plain old HTML open directory, which OD-DB was designed for

**Closed by terorie** 2019-02-10 23:10 UTC
